<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net8</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugin</RootNamespace>
		<Deterministic>false</Deterministic>
		<AssemblyTitle>PepperDash.Essentials.Plugin.WyreStorm.NetworkHD</AssemblyTitle>
		<Company>PepperDash Technology</Company>
		<Description>Essentials plugin for WyreStorm NetworkHD devices.</Description>
		<Copyright>Copyright 2025</Copyright>
		<Version>1.0.0-local</Version>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<InformationalVersion>$(Version)</InformationalVersion>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<Authors>PepperDash Technology</Authors>
		<PackageId>PepperDash.Essentials.Plugin.WyreStorm.NetworkHD</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-wyrestorm-networkHD.git</PackageProjectUrl>
		<PackageTags>crestron 4series essentials plugin wyrestorm networkhd</PackageTags>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);SERIES4</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Properties\**" />
		<EmbeddedResource Remove="Properties\**" />
		<None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
    <None Remove="epi-wyrestorm-networkHD.projectinfo" />
  </ItemGroup>

  <ItemGroup>
 	<PackageReference Include="PepperDashEssentials" Version="3.0.0-fix-surface-masked-device-instantiation-errors.1" >
  		<ExcludeAssets>runtime</ExcludeAssets>
 	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="../output\epi-wyrestorm-networkHD.4Series.1.0.0-local.cplz" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="../output\epi-wyrestorm-networkHD.4Series.1.0.0-local.cplz" />
  </ItemGroup>
</Project>
